name: Plugin Tests

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  php-syntax:
    name: PHP Syntax Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Check PHP syntax
        run: find . -name "*.php" -not -path "./vendor/*" -not -path "./node_modules/*" -exec php -l {} \;

  wordpress-coding-standards:
    name: WordPress Coding Standards
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run PHPCS
        run: composer phpcs

  plugin-check:
    name: Plugin Check
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          extensions: mysqli

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            sleep 1
          done

      - name: Setup WordPress
        run: |
          mkdir -p /tmp/wordpress
          cd /tmp/wordpress
          wp core download --allow-root
          wp config create --dbname=test --dbuser=root --dbpass=root --dbhost=127.0.0.1 --allow-root
          wp core install --url=http://localhost --title=Test --admin_user=admin --admin_password=admin --admin_email=test@test.com --skip-email --allow-root

      - name: Validate readme.txt
        run: |
          if [ -f "readme.txt" ]; then
            # Check for required headers
            grep -q "=== Gift Message for Woo ===" readme.txt || echo "Warning: Plugin name header missing"
            grep -q "Stable tag:" readme.txt || echo "Warning: Stable tag missing"
            grep -q "License:" readme.txt || echo "Warning: License missing"
          fi

  assets-check:
    name: Check Assets
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for required assets
        run: |
          # Check if assets directory exists
          if [ -d ".wordpress-org" ]; then
            echo "Assets directory found"
            
            # Check for banner
            if ls .wordpress-org/banner-* 1> /dev/null 2>&1; then
              echo "✓ Banner found"
            else
              echo "⚠ No banner found"
            fi
            
            # Check for icon
            if ls .wordpress-org/icon-* 1> /dev/null 2>&1; then
              echo "✓ Icon found"
            else
              echo "⚠ No icon found"
            fi
            
            # Check for screenshots
            if ls .wordpress-org/screenshot-* 1> /dev/null 2>&1; then
              echo "✓ Screenshots found"
            else
              echo "⚠ No screenshots found"
            fi
          else
            echo "No assets directory found"
          fi